name: med_vqa
channels:
  - huggingface
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-image
  - pandas
  - pillow
  - pytorch::pytorch-cuda=11.8
  - torchvision
  - huggingface::datasets
  - transformers
  - peft
  - sentencepiece
  - gdown
  - matplotlib
  - seaborn
  - notebook
  - ipykernel
  - ipywidgets
  - tqdm
  - pip
  - pip:
    - git+https://github.com/openai/CLIP.git

